"""CV YAML→LaTeX generator. Reads data/*.yaml, validates, renders templates,
writes generated/*.tex. Run: `uv run python build.py` or `make data`."""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Literal

import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined
from pydantic import BaseModel, Field, ValidationError, field_validator

ROOT = Path(__file__).parent
DATA_DIR = ROOT.parent / "data"
TEMPLATES_DIR = ROOT / "templates"
GENERATED_DIR = ROOT / "generated"

BANNER = (
    "% AUTOGENERATED FROM data/{section}.yaml — DO NOT EDIT.\n"
    "% Edit the YAML and run `make data` (or `python build.py`).\n"
)


# --- Models ---------------------------------------------------------------

class Honor(BaseModel):
    name: str
    year: str  # may be a year, range, or compound like "2013, 2014, 2015"


class Grant(BaseModel):
    title: str
    agency: str
    amount: str  # display string, e.g. "$500,000"; the `$` is LaTeX-escaped
    role: str | None = None  # e.g. PI / co-PI; carried, not rendered yet
    year: str | None = None  # carried, not rendered yet


class Education(BaseModel):
    degree: str
    field: str | None = None
    institution: str
    year: str | None = None
    notes: str | None = None


class Teaching(BaseModel):
    course: str
    role: str
    institution: str
    term: str | None = None
    highlight: str | None = None  # optional red note under the entry (e.g. a rating)


class Mentee(BaseModel):
    name: str
    project: str
    current: str | None = None
    years: str


class LeadershipRole(BaseModel):
    role: str
    org: str
    years: str


class MentoringSection(BaseModel):
    mentees: list[Mentee] = Field(default_factory=list)
    other: list[str] = Field(default_factory=list)
    leadership: list[LeadershipRole] = Field(default_factory=list)


class OrgRole(BaseModel):
    venue: str
    year: str
    detail: str | None = None
    role: str


class ServiceSection(BaseModel):
    organization: list[OrgRole] = Field(default_factory=list)
    refereeing: dict[str, list[int]] = Field(default_factory=dict)


class SubsectionItem(BaseModel):
    org: str
    link: str | None = None
    text: str


class Subsection(BaseModel):
    heading: str
    items: list[SubsectionItem]


class Experience(BaseModel):
    org: str
    role: str
    context: str
    dates: str | None = None
    bullets: list[str] = Field(default_factory=list)
    subsections: list[Subsection] = Field(default_factory=list)


class Author(BaseModel):
    name: str
    me: bool = False
    equal: bool = False  # co-first-author asterisk
    dagger: bool = False  # e.g. co-advisor / corresponding (†)


# Sentinel for ellipses in author lists — represented as the literal string "...".
ELLIPSIS = "..."


def _parse_author(raw):
    """A bare YAML string is shorthand for {name: <string>}, except `'...'` (the
    abbreviated-list ellipsis sentinel). Two website-only tokens are dropped for
    the CV (returning None, filtered by the validator): a forced line-break marker
    (`//` / `\\`) and a name-less `{affil: ...}` glyph entry."""
    if isinstance(raw, str):
        if raw == ELLIPSIS:
            return ELLIPSIS
        if raw.strip() in ("//", "\\", "\\\\"):
            return None
        return Author(name=raw)
    if isinstance(raw, dict) and not raw.get("name") and raw.get("affil"):
        return None
    return Author.model_validate(raw)


class Links(BaseModel):
    arxiv: str | None = None
    pdf: str | None = None
    doi: str | None = None
    ieee: str | None = None
    github: str | None = None
    project: str | None = None


class IdentityModel(BaseModel):
    name: str
    title: str
    affiliation: str
    email: str
    website: str
    tagline: str
    headshot: str
    alt: str
    links: dict[str, str | None]


PubType = Literal["preprint", "journal", "conference", "workshop"]


class Publication(BaseModel):
    year: int
    type: PubType
    authors: list  # list of Author or ELLIPSIS string
    title: str
    venue: str
    venue_full: str | None = None
    links: Links = Field(default_factory=Links)
    awards: list[str] = Field(default_factory=list)
    # CV-only award rendering. When `cv_award` is set it replaces the verbose
    # `awards` strings in the CV: a short red label (e.g. "Best Paper Award",
    # "Finalist"), optionally followed by `cv_award_venue` styled like a venue
    # (e.g. "ROAR Workshop @ RSS") for awards won at a workshop whose parent
    # conference differs from the paper's own venue. The website ignores both.
    cv_award: str | None = None
    cv_award_venue: str | None = None

    @field_validator("authors", mode="before")
    @classmethod
    def _coerce_authors(cls, v):
        if not isinstance(v, list):
            raise ValueError("authors must be a list")
        return [p for p in (_parse_author(a) for a in v) if p is not None]


# --- Manifest -------------------------------------------------------------
# (section, model, shape) where shape ∈ {"list", "root", "publications"}.
SECTIONS: list[tuple[str, type, str]] = [
    ("identity", IdentityModel, "root"),
    ("honors", Honor, "list"),
    ("grants", Grant, "list"),
    ("education", Education, "list"),
    ("teaching", Teaching, "list"),
    ("mentoring", MentoringSection, "root"),
    ("service", ServiceSection, "root"),
    ("experience", Experience, "list"),
    ("publications", Publication, "publications"),
]


# --- Helpers --------------------------------------------------------------

def make_env() -> Environment:
    """Jinja2 env with LaTeX-friendly delimiters that don't clash with `{}`."""
    env = Environment(
        loader=FileSystemLoader(TEMPLATES_DIR),
        block_start_string=r"\BLOCK{",
        block_end_string="}",
        variable_start_string=r"\VAR{",
        variable_end_string="}",
        comment_start_string=r"\#{",
        comment_end_string="}",
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
        undefined=StrictUndefined,
        autoescape=False,
    )
    env.globals["format_authors"] = format_authors
    env.globals["format_links"] = format_links
    env.filters["latex_escape"] = latex_escape
    return env


def latex_escape(s) -> str:
    """Escape text for LaTeX macro values."""
    replacements = {
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
        "\\": r"\textbackslash{}",
    }
    return "".join(replacements.get(ch, ch) for ch in str(s))


def load_yaml(path: Path):
    if not path.exists():
        raise FileNotFoundError(f"Missing data file: {path}")
    with path.open() as f:
        return yaml.safe_load(f)


def validate(data, model: type, path: Path):
    """Validate a list-of-dicts payload against `list[model]`."""
    if data is None:
        return []
    if not isinstance(data, list):
        raise ValueError(f"{path}: expected a YAML list at the root")
    out = []
    for i, item in enumerate(data):
        try:
            out.append(model.model_validate(item))
        except ValidationError as e:
            raise SystemExit(f"\n{path} entry {i}: {e}\n")
    return out


def validate_root(data, model: type, path: Path):
    """For sections whose YAML root is a dict matching `model`."""
    if data is None:
        return model()
    try:
        return model.model_validate(data)
    except ValidationError as e:
        raise SystemExit(f"\n{path}: {e}\n")


def format_authors(authors: list) -> str:
    """Render a list of Author/ELLIPSIS entries as a LaTeX-ready citation string.

    Joiner is comma+space; the last separator is `, \\&` (Oxford-comma + ampersand).
    `me=True` wraps the name in `\\textbf{...}`. `equal=True` adds a trailing `*`
    OUTSIDE any `\\textbf` wrap (e.g. `\\textbf{R. Scalise}*`).

    Exception: if the list contains any ellipsis (`...`), it's an abbreviated list —
    use comma joiners throughout (no `\\&`), since "..., \\& ..." reads as
    ungrammatical (an "and" before a literal ellipsis).
    """
    pieces = []
    for a in authors:
        if a == ELLIPSIS:
            pieces.append("...")
        else:
            name = f"\\textbf{{{a.name}}}" if a.me else a.name
            if a.equal:
                name = name + "*"
            if a.dagger:
                name = name + "\\dag"
            pieces.append(name)
    if not pieces:
        return ""
    if len(pieces) == 1:
        out = pieces[0]
    elif ELLIPSIS in pieces:
        out = ", ".join(pieces)
    else:
        out = ", ".join(pieces[:-1]) + ", \\& " + pieces[-1]
    # Always terminate with a single period. Avoid double-dotting if the list
    # ends in an ellipsis (`...` already ends in a period).
    return out if out.endswith(".") else out + "."


def format_links(links: Links) -> str:
    """Emit `\\href{url}{[label]}` for each present link, in fixed order:
    arxiv, pdf, doi, ieee, github, project."""
    parts = []
    if links.arxiv:
        url = links.arxiv if links.arxiv.startswith("http") else f"https://arxiv.org/abs/{links.arxiv}"
        parts.append(f"\\href{{{url}}}{{[arxiv]}}")
    if links.pdf:
        parts.append(f"\\href{{{links.pdf}}}{{[pdf]}}")
    if links.doi:
        parts.append(f"\\href{{https://doi.org/{links.doi}}}{{[doi]}}")
    if links.ieee:
        parts.append(f"\\href{{{links.ieee}}}{{[ieee]}}")
    if links.github:
        url = links.github if links.github.startswith("http") else f"https://github.com/{links.github}"
        parts.append(f"\\href{{{url}}}{{[github]}}")
    if links.project:
        parts.append(f"\\href{{{links.project}}}{{[project]}}")
    return " ".join(parts)


def render_section_list(env: Environment, section: str, model: type) -> str:
    yaml_path = DATA_DIR / f"{section}.yaml"
    raw = load_yaml(yaml_path)
    entries = validate(raw, model, yaml_path)
    template = env.get_template(f"{section}.tex.j2")
    body = template.render(entries=entries)
    return BANNER.format(section=section) + body


def render_section_root(env: Environment, section: str, model: type) -> str:
    yaml_path = DATA_DIR / f"{section}.yaml"
    raw = load_yaml(yaml_path)
    data = validate_root(raw, model, yaml_path)
    template = env.get_template(f"{section}.tex.j2")
    body = template.render(data=data)
    return BANNER.format(section=section) + body


def render_publications(env: Environment) -> str:
    yaml_path = DATA_DIR / "publications.yaml"
    raw = load_yaml(yaml_path) or []
    if not isinstance(raw, list):
        raise SystemExit(f"{yaml_path}: expected a YAML list at the root")
    pubs: list[Publication] = []
    for i, item in enumerate(raw):
        try:
            pubs.append(Publication.model_validate(item))
        except ValidationError as e:
            raise SystemExit(f"\n{yaml_path} entry {i}: {e}\n")
    groups: dict[str, list[Publication]] = {
        "preprint": [], "journal": [], "conference": [], "workshop": [],
    }
    for p in pubs:
        groups[p.type].append(p)
    for k in groups:
        groups[k].sort(key=lambda p: -p.year)
    body = env.get_template("publications.tex.j2").render(groups=groups)
    return BANNER.format(section="publications") + body


def write_generated(section: str, content: str) -> None:
    out_path = GENERATED_DIR / f"{section}.tex"
    out_path.write_text(content)
    print(f"wrote {out_path.relative_to(ROOT)}")


def main() -> int:
    GENERATED_DIR.mkdir(exist_ok=True)
    env = make_env()
    for section, model, shape in SECTIONS:
        if not (DATA_DIR / f"{section}.yaml").exists():
            print(f"skip {section} — no data file yet")
            continue
        if not (TEMPLATES_DIR / f"{section}.tex.j2").exists():
            print(f"skip {section} — no template yet")
            continue
        if shape == "publications":
            content = render_publications(env)
        elif shape == "list":
            content = render_section_list(env, section, model)
        else:
            content = render_section_root(env, section, model)
        write_generated(section, content)
    return 0


if __name__ == "__main__":
    sys.exit(main())
